#!/usr/bin/env python3
"""gen_tree.py -- generate the G+Smo core library map (deterministic).

Walks src/ modules, examples/ and unittests/, extracts each file's @brief from
its doxygen header, and writes <gismo-root>/.claude/gismo-maps/library-map.md.

Usage: gen_tree.py [--root <gismo-root>]
"""
import os
import re
import sys

BRIEF_RE = re.compile(r"@brief\s+(.*?)(?:\n\s*\n|\*/|\n\s*@)", re.S)


def find_root(start):
    d = os.path.abspath(start)
    while d != "/":
        if os.path.isfile(os.path.join(d, "CMakeLists.txt")) and \
           os.path.isdir(os.path.join(d, "src", "gsCore")):
            return d
        d = os.path.dirname(d)
    sys.exit("gen_tree: not inside a G+Smo checkout")


def brief_of(path):
    try:
        with open(path, errors="replace") as f:
            head = f.read(2000)
    except OSError:
        return ""
    m = BRIEF_RE.search(head)
    if not m:
        return ""
    return " ".join(m.group(1).split())


def md_escape(s):
    return s.replace("|", "\\|")


def main():
    root = None
    args = sys.argv[1:]
    if args[:1] == ["--root"] and len(args) > 1:
        root = os.path.abspath(args[1])
    if root is None:
        root = find_root(os.getcwd())

    out = []
    out.append("# G+Smo core library map")
    out.append("")
    out.append("<!-- GENERATED by the gismo:tree skill (gen_tree.py) -- do not edit by hand; regenerate instead -->")
    out.append("")
    out.append("Layout: `src/<module>/` holds headers (`.h` interface, `.hpp` template "
               "implementation, `*_.cpp` explicit instantiation). `examples/` are runnable "
               "drivers (target = file basename without `.cpp`). `unittests/` are UnitTest++ "
               "suites (suite name = file basename). Optional modules live in `optional/` -- "
               "see the gismo:module-map skill for those.")
    out.append("")

    src = os.path.join(root, "src")
    for module in sorted(os.listdir(src)):
        mdir = os.path.join(src, module)
        if not os.path.isdir(mdir):
            continue
        headers = sorted(f for f in os.listdir(mdir) if f.endswith(".h"))
        out.append("## src/%s (%d headers)" % (module, len(headers)))
        out.append("")
        for h in headers:
            b = brief_of(os.path.join(mdir, h))
            out.append("- `%s`%s" % (h, " -- " + md_escape(b) if b else ""))
        subdirs = sorted(d for d in os.listdir(mdir)
                         if os.path.isdir(os.path.join(mdir, d)))
        for sd in subdirs:
            sub_headers = sorted(f for f in os.listdir(os.path.join(mdir, sd))
                                 if f.endswith(".h"))
            if sub_headers:
                out.append("- `%s/`: %s" % (sd, ", ".join("`%s`" % f for f in sub_headers)))
        out.append("")

    for section, dirname, suffix in (("Examples", "examples", ".cpp"),
                                     ("Unit tests", "unittests", "_test.cpp")):
        d = os.path.join(root, dirname)
        if not os.path.isdir(d):
            continue
        files = sorted(f for f in os.listdir(d) if f.endswith(suffix))
        out.append("## %s (%s/, %d files)" % (section, dirname, len(files)))
        out.append("")
        for f in files:
            b = brief_of(os.path.join(d, f))
            out.append("- `%s`%s" % (f, " -- " + md_escape(b) if b else ""))
        out.append("")

    # Per-checkout data: written into the project, never into the skill/plugin
    # (one plugin install serves many worktrees).
    dest = os.path.normpath(os.path.join(root, ".claude", "gismo-maps",
                                         "library-map.md"))
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    with open(dest, "w") as f:
        f.write("\n".join(out))
    print("wrote %s (%d lines)" % (dest, len(out)))
    print("STATUS: OK")


if __name__ == "__main__":
    main()
