#!/usr/bin/env python3
"""gen_module_map.py -- generate per-submodule context files (deterministic).

For every module under optional/ writes
<gismo-root>/.claude/gismo-maps/modules/<name>.md containing: README summary,
whether it is enabled in submodules.txt, whether it has its own git repo, src/
headers with @brief lines, unittest suites, and example targets. Also writes
modules/index.md (one line per module).

Usage: gen_module_map.py [--root <gismo-root>]
"""
import os
import re
import sys

BRIEF_RE = re.compile(r"@brief\s+(.*?)(?:\n\s*\n|\*/|\n\s*@)", re.S)


def find_root(start):
    d = os.path.abspath(start)
    while d != "/":
        if os.path.isfile(os.path.join(d, "CMakeLists.txt")) and \
           os.path.isdir(os.path.join(d, "src", "gsCore")):
            return d
        d = os.path.dirname(d)
    sys.exit("gen_module_map: not inside a G+Smo checkout")


def brief_of(path):
    try:
        with open(path, errors="replace") as f:
            head = f.read(2000)
    except OSError:
        return ""
    m = BRIEF_RE.search(head)
    return " ".join(m.group(1).split()) if m else ""


def md_escape(s):
    return s.replace("|", "\\|")


def readme_summary(mdir, max_lines=12):
    for name in ("README.md", "README.txt", "README"):
        p = os.path.join(mdir, name)
        if os.path.isfile(p):
            with open(p, errors="replace") as f:
                lines = f.read().splitlines()
            # First non-badge, non-heading paragraph.
            para, in_para = [], False
            for ln in lines:
                s = ln.strip()
                if not s:
                    if in_para:
                        break
                    continue
                if s.startswith(("#", "[![", "![", "|", "<img", "<!--")):
                    if in_para:
                        break
                    continue
                para.append(s)
                in_para = True
                if len(para) >= max_lines:
                    break
            return " ".join(para)
    return ""


def enabled_submodules(root):
    p = os.path.join(root, "submodules.txt")
    if not os.path.isfile(p):
        return set()
    result = set()
    with open(p, errors="replace") as f:
        for line in f:
            if line.lstrip().startswith("#"):  # skip commented examples
                continue
            m = re.search(r'set\(SUBMODULES_TXT\s+"([^"]*)"\)', line)
            if m:
                result.update(x for x in m.group(1).split(";") if x)
    return result


def list_briefed(d, suffix):
    if not os.path.isdir(d):
        return []
    return [(f, brief_of(os.path.join(d, f)))
            for f in sorted(os.listdir(d)) if f.endswith(suffix)]


def gen_module(root, name, enabled, outdir):
    mdir = os.path.join(root, "optional", name)
    out = []
    out.append("# optional/%s" % name)
    out.append("")
    out.append("<!-- GENERATED by the gismo:module-map skill (gen_module_map.py) -- regenerate, do not hand-edit -->")
    out.append("")
    facts = []
    facts.append("enabled in submodules.txt: %s" % ("YES" if name in enabled else "no"))
    facts.append("own git repo: %s" % ("YES" if os.path.isdir(os.path.join(mdir, ".git")) else "no"))
    for extra in ("examples", "unittests", "filedata", "tutorials", "python_examples"):
        if os.path.isdir(os.path.join(mdir, extra)):
            facts.append("has %s/" % extra)
    out.append("; ".join(facts))
    out.append("")
    rs = readme_summary(mdir)
    if rs:
        out.append("**Summary (README):** " + rs)
        out.append("")

    # Headers: top-level and src/ (recursively one level of subdirs).
    hdr_sections = []
    top = [(f, brief_of(os.path.join(mdir, f)))
           for f in sorted(os.listdir(mdir)) if f.endswith(".h")]
    if top:
        hdr_sections.append(("", top))
    srcdir = os.path.join(mdir, "src")
    if os.path.isdir(srcdir):
        hdr_sections.append(("src/", list_briefed(srcdir, ".h")))
        for sd in sorted(os.listdir(srcdir)):
            p = os.path.join(srcdir, sd)
            if os.path.isdir(p):
                items = list_briefed(p, ".h")
                if items:
                    hdr_sections.append(("src/%s/" % sd, items))
    for prefix, items in hdr_sections:
        if not items:
            continue
        out.append("## Headers %s" % prefix)
        out.append("")
        for f, b in items:
            out.append("- `%s%s`%s" % (prefix, f, " -- " + md_escape(b) if b else ""))
        out.append("")

    tests = list_briefed(os.path.join(mdir, "unittests"), "_test.cpp")
    if tests:
        out.append("## Unit-test suites (compile into the main `unittests` binary when enabled)")
        out.append("")
        for f, b in tests:
            out.append("- suite `%s`%s" % (f[:-4], " -- " + md_escape(b) if b else ""))
        out.append("")

    examples = list_briefed(os.path.join(mdir, "examples"), ".cpp")
    if examples:
        out.append("## Examples (make target = basename)")
        out.append("")
        for f, b in examples:
            out.append("- `%s`%s" % (f[:-4], " -- " + md_escape(b) if b else ""))
        out.append("")

    dest = os.path.join(outdir, name + ".md")
    with open(dest, "w") as f:
        f.write("\n".join(out))
    return rs or "(no README summary)"


def main():
    root = None
    args = sys.argv[1:]
    if args[:1] == ["--root"] and len(args) > 1:
        root = os.path.abspath(args[1])
    if root is None:
        root = find_root(os.getcwd())

    opt = os.path.join(root, "optional")
    # Per-checkout data: written into the project, never into the skill/plugin
    # (one plugin install serves many worktrees).
    outdir = os.path.normpath(os.path.join(root, ".claude", "gismo-maps", "modules"))
    os.makedirs(outdir, exist_ok=True)

    enabled = enabled_submodules(root)
    index = ["# Optional modules index",
             "",
             "<!-- GENERATED by gen_module_map.py -->",
             "",
             "Per-module details in `<name>.md` next to this file. Modules marked "
             "[enabled] are active via submodules.txt in this checkout.",
             ""]
    count = 0
    for name in sorted(os.listdir(opt)):
        mdir = os.path.join(opt, name)
        if not os.path.isdir(mdir) or not os.path.isfile(os.path.join(mdir, "CMakeLists.txt")):
            continue
        summary = gen_module(root, name, enabled, outdir)
        tag = " [enabled]" if name in enabled else ""
        short = summary if len(summary) < 220 else summary[:217] + "..."
        index.append("- [%s](%s.md)%s -- %s" % (name, name, tag, md_escape(short)))
        count += 1

    with open(os.path.join(outdir, "index.md"), "w") as f:
        f.write("\n".join(index) + "\n")
    print("wrote %d module files + index.md to %s" % (count, outdir))
    print("STATUS: OK")


if __name__ == "__main__":
    main()
